language: python
sudo: required
python:
  - "2.7"
before_install:
  - sudo apt-get install -qq -y swig python-dev
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt
# # command to run tests, e.g. python setup.py test
script: python salinity/manage.py test salinity_front
