language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install --quiet -r requirements.txt
# # command to run tests, e.g. python setup.py test
script: python salinity/manage.py test salinity_front
